apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-exports
  namespace: lumina
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 8Gi
