apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: lumina
spec:
  dnsNames:
    - frontend.codezap.win
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretName: selfsigned-cert
