apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-codezap-win-tls
  namespace: lumina # ต้องอยู่ใน namespace เดียวกับ Gateway
spec:
  secretName: frontend-codezap-win-tls # ชื่อนี้ต้องตรงกับ certificateRefs ใน Gateway
  duration: 24h
  renewBefore: 12h
  commonName: frontend.codezap.win
  dnsNames:
  - frontend.codezap.win
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  # หากใช้ HTTP Challenge ต้องระบุ routeType (สำหรับ Gateway API)
  # หรือปล่อยว่างหากใช้ DNS Challenge   
