apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-resources
spec:
  validationFailureAction: Audit # Audit is logged in a PolicyReport or ClusterPolicyReport / Enforce is blocked when the resource does not comply
  background: true
  rules:
  - name: validate-resource-limits
    match:
      any:
      - resources:
          kinds:
          - Pod
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - istio-system
          - kyverno
          - logging
          - flux-system
    validate:
      message: "ต้องกำหนด resources.requests และ resources.limits (cpu, memory) ใน Pod ทุกครั้ง"
      pattern:
        spec:
          containers:
          - resources:
              requests:
                cpu: "?*"
                memory: "?*"
              limits:
                cpu: "?*"
                memory: "?*"
