apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager-config
    namespace: flux-system
  interval: 30m0s
  path: ./app/base
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: lumina
  timeout: 3m0s
  wait: true
