apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-repo.yaml
  - vector-repo.yaml
  - quickwit-repo.yaml
  - weave-gitops-dashboard.yaml
  - nfs-repo.yaml
  - observability.yaml
  - app.yaml
  - external-secrets-repo.yaml
