apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system-automation.yaml
- frontend-automation.yaml
- frontend-policy.yaml
- frontend-registry.yaml
- backend-automation.yaml
- backend-policy.yaml
- backend-registry.yaml
