---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: backend
  namespace: lumina
spec:
  image: ghcr.io/traipoap/backend
  interval: 5m0s
  secretRef:
    name: github-registry
