apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vector-source.yaml
- vector-release.yaml
namespace: lumina
patches:
- target:
    kind: Service
    name: vector
  path: vector-service-patch.yaml
