---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vector-repo.yaml
  - quickwit-repo.yaml
  - ../infrastructure/
  - git-repo.yaml
  - weave-gitops-dashboard.yaml
  - nfs-repo.yaml
