---
apiVersion: v1
kind: Namespace
metadata:
  name: lumina
  labels:
    istio.io/dataplane-mode: ambient

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: quickwit-repo
  namespace: lumina
spec:
  interval: 1m0s
  timeout: 3m0s
  url: https://helm.quickwit.io
