---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h0m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      version: '>=2.10.0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: external-secrets
  storageNamespace: external-secrets
  targetNamespace: external-secrets
  upgrade:
    crds: CreateReplace
