---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
spec:
  interval: 1h0m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: '>=2.10.0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: external-secrets
  upgrade:
    crds: CreateReplace

  values:
    extraEnv:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: awssm-secret
            key: KEYID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: awssm-secret
            key: SECRETKEY
