apiVersion: batch/v1
kind: Job
metadata:
  name: quickwit-create-index
  namespace: lumina
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-index
          image: curlimages/curl:latest
          args:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Quickwit to be ready..."
              until curl -s http://quickwit-searcher:7280/api/v1/version; do
                sleep 5;
              done

              echo "Checking if index 'syslogs' exists..."
              if curl -s -f http://quickwit-searcher:7280/api/v1/indexes/syslogs > /dev/null 2>&1; then
                echo "Index already exists, skipping creation."
                exit 0  # <--- ออกจากสคริปต์ทันที: ถ้ามี syslogs indexes อยู่แล้ว
              fi

              echo "Index not found. Creating index..."
              RESPONSE=$(curl -s -w "\n%{http_code}" -X POST http://quickwit-searcher:7280/api/v1/indexes \
                --header "content-type: application/yaml" \
                --data-binary @/config/quickwit.yaml)

              HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
              BODY=$(echo "$RESPONSE" | sed '$d')

              if [ "$HTTP_CODE" -eq 200 ] || [ "$HTTP_CODE" -eq 201 ]; then
                echo "Index created successfully."
              else
                echo "Failed to create index: $BODY"
                exit 1 # ให้ Job ล้มเหลวถ้าสร้างไม่สำเร็จ เพื่อจะได้ Retry
              fi
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: quickwit-indexer
