apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: frontend-policy
  namespace: flux-system
spec:
  secretRef:
    name: app-git-secret
  imageRepositoryRef:
    name: frontend  # deployment name
  policy:            # <--- ต้องมี colon
    semver:          # <--- ต้องเยื้องใต้ policy
      range: ">=0.0.0" # <--- เปลี่ยนเป็น >=0.0.0 เพื่อรับ tag 0.0.x จาก GitHub Actions
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: backend-policy
  namespace: flux-system
spec:
  secretRef:
    name: app-git-secret
  imageRepositoryRef:
    name: backend  # deployment name
  policy:            # <--- ต้องมี colon
    semver:          # <--- ต้องเยื้องใต้ policy
      range: ">=0.0.0" # <--- เปลี่ยนเป็น >=0.0.0 เพื่อรับ tag 0.0.x จาก GitHub Actions
