apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: quickwit
  namespace: lumina
spec:
  interval: 30m0s
  path: ./infrastructure/logging/quickwit
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: quickwit
  targetNamespace: lumina
  timeout: 3m0s
  wait: true
