apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: vector
    meta.helm.sh/release-namespace: lumina
  creationTimestamp: "2026-08-19T03:37:24Z"
  labels:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.57.0-distroless-libc
    helm.sh/chart: vector-0.57.0
    helm.toolkit.fluxcd.io/name: vector
    helm.toolkit.fluxcd.io/namespace: lumina
  name: vector
  namespace: lumina
  resourceVersion: "2035806"
  uid: 5a888796-c935-476e-be54-2709ecfcf60d
spec:
  clusterIP: 10.43.155.3
  clusterIPs:
  - 10.43.155.3
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api
    nodePort: 30868
    port: 8686
    protocol: TCP
    targetPort: 8686
  - name: syslog-tcp
    nodePort: 30514
    port: 514
    protocol: TCP
    targetPort: 514
  - name: syslog-udp
    nodePort: 30514
    port: 514
    protocol: UDP
    targetPort: 514
  selector:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
