---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: letsencrypt-external-secret
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: letsencrypt-secret-values
    template:
      engineVersion: v2
      data:
        values.yaml: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloudflare-api-key-secret
            namespace: production
          type: Opaque
          stringData:
            api-key: "{{ .api-token }}"
  data:
    - secretKey: api-token
      remoteRef:
        key: prod/tls/frontend
        property: cloudflare-api-token
