apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore-aws
  namespace: lumina
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: KEYID
          secretAccessKeySecretRef:
            name: awssm-secret
            key: SECRETKEY
