---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quickwit-indexer
data:
  quickwit.yaml: |
    version: 0.8
    index_id: syslogs
    doc_mapping:
      field_mappings:
        - name: source_ip
          type: ip
          stored: true
          indexed: true
          fast: true
          description: "Source IP address of the connection"
        - name: message
          type: text
          tokenizer: default
          record: position
          stored: true
          indexed: true
          fieldnorms: false
          description: "Log message content"
        - name: timestamp
          type: datetime
          input_formats:
            - rfc3339
          output_format: unix_timestamp_millis
          fast: true
          fast_precision: milliseconds
          stored: true
          description: "Event time (when it happened)"
        - name: index_timestamp
          type: datetime
          input_formats:
            - unix_timestamp
          output_format: unix_timestamp_nanos
          fast: true
          fast_precision: nanoseconds
          stored: true
          description: "Timestamp when the event was ingested by Vector"
      timestamp_field: timestamp
    search_settings:
      default_search_fields: [source_ip, message]
    indexing_settings:
      commit_timeout_secs: 30
    retention:
      period: 90 days
      schedule: daily
