apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-codezap-win-tls
  namespace: lumina
spec:
  secretName: frontend-codezap-win-tls
  duration: 24h
  renewBefore: 12h
  commonName: frontend.codezap.win
  dnsNames:
  - frontend.codezap.win
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
