apiVersion: v1
kind: ConfigMap
metadata:
  name: lumina-config
  namespace: lumina
data:
  # Frontend configuration
  ALLOWED_HOSTS: "frontend.codezap.win,.codezap.win"
  API_PROXY_TARGET: "http://backend-svc:8080"

  # Backend configuration
  BACKEND_PORT: "8080"
  CORS_ORIGINS: "https://frontend.codezap.win"
  QUICKWIT_URL: "http://quickwit-searcher:7280"

  # Database configuration
  DATABASE_PATH: "backend/data/users.db"
