---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-registry
  namespace: lumina
spec:
  encryptedData:
    .dockerconfigjson: AgBHmXMf/Q3r5cMQs2NaIQDqdsp5Muv0K7rbzGaOhQNEpWT1i2hwEXpJlMWSvKWET/Y2uCXQ0lhpf3ap+kbW39Mu8PvGNjJjIKAxcSBE6/PHyQiVeLESbjlPmPQup/D8x/RSy7KV/N0ubTJs2QzPnczfm25hIX0uZYZ9DjvYXX306Raq5oklqNCNqyIPAWztCNMDET2C/xFxsMm6C6zLDvGwdYO6Jar6D0Vu74MKz94y/xatcB/nnobn/c/6NAmHTlIIIqpqMy/rBUbKAiqivdXZBoH9PHqdx9sOzAmbhhF8+gnTmJwKwGCxtahrOuFifavrhNWfjzYiv4GOmONpge7uzlKkwxXVfbHqKi9ui4ZczBIy4aU/o4xL7T/XlDaRZShhOprH+y4NekWztv890jCcruthJ4ycw1nDPUYiSYGdI7Jt+YLwzA2oSVCfwIuVJ03webtkdWg+lLvgW8LHPakz58I9e/FRGY73A9mePNMUhwbAGYxQIZN1pRWTGDM6bMTjh/NwdJeLO7XO+oXd6S7N1nr3qeYDfoIRMLXwDF296W0MLpm1FNhB9VE1kdNVndKhyRNCQO+nDWd5FdfmJVOPslZO3dLXxn5pmAkBM45JNPnqkCWEDL5aIsVbStXuTgNRtgtW48EHsD9HkdqBfrAebP9QhLeZeFeASauZLfK5e78fPMDJnpxaWy4l/aNQKcJ6EmAn+lTDurgPiwiG53WNcdzT8voT9TutLdckBPepAu4uQmwCeS03zVq5qpXARRl4rQPwBI0qsLrFjUUVjNbrkyGG4gpzn8IijOAyTvm6Oi1lhmOyL4pYtC07B+Ph/Jg/Q2zcmxsy/heW7Lan2RkJCWsujXETlOJwCJwjVcqWdApOiafYOK9msS4k0BoHduSLSEwLtsIKqDUHEtv6XiuVhxRf3k7y/fxFIgU4sW228KAPSQmTpXUMSdXBjzUIvFEcfrEddAzzQ+0uXopqtweZ
  template:
    metadata:
      name: github-registry
      namespace: lumina
    type: kubernetes.io/dockerconfigjson
