---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: lumina
spec:
  encryptedData:
    JWT_SECRET: CHANGE_ME92TWJgsTV7X9r64ApCeTsLZ0dPB78ItKclwnw47z/RzbQHIdvWKAgac6rAqQCTaKbAYoqYjwKSXgxCtuk6Qz4VbrkryjmiHKMqgtOZWeJDxQwcVPbf+U0VMa1u9l/P7Ylm+yATtEpNfEWG0POA5nNcjTCdNoVNDnKZGa8petsh6iavlAnLDfLne0Zauh5TI9cr6NTNareXtDzifWB52p7T0W5p7rDaKavplPfSQqhzWW19sIH11j+whpYI20CQPop1Hjm1JyfoQkb3JuJxXD6KStgXgzHQ9SoQ5YqXFb5rqlyPlEBK+WD8KHtxNATLPr7tXgiAy9s8PmQ1WW81BuxaUOY8LcBuq5nTWj5B2Ceaefj1Fh3Kc+Tfmdy+X8JZW4ql7fGSazT1dXfnkIXxdhXNkNvlgAYrO1U+mmVmQ9XtXiPF4hq/MFXJpTVHzCM8qt3wI1CAIDdMTbzfT7amO25Yx3Bs+6oxKhzmXlJFto4r0N4vwXI4KkjDXUfE5W62bnVhyP9r6PpuVq8CY0pP3iOhxducZNZX5MQU5nyVaLQUV6e/aAGPFmQxnc9fCiRvkd+PKjfJksJ5OKaxAhqUxGQx2lJY70/uP5zT45jxlRgnJdv5da2LABLSfw+srfaYlVf3nlg3Zkes717+hGz8C+AU/OvN5Tn5NJ/WMyVjrVhgmlf2mdpyQf
  template:
    metadata:
      name: jwt-secret
      namespace: lumina
