apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-codezap-win-tls
spec:
  secretName: app-codezap-win-tls
  dnsNames:
  - "app.codezap.win"
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
