apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: app-gateway
  annotations:
    cert-manager.io/cluster-issuer: "cluster-ca"
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "app.codezap.win"
    allowedRoutes:
      namespaces:
        from: "All"

  - name: https
    protocol: HTTPS
    port: 443
    hostname: "app.codezap.win"
    tls:
      mode: Terminate
      certificateRefs:
      - name: app-codezap-win-tls
        kind: Secret
    allowedRoutes:
      namespaces:
        from: All

  - name: mesh
    port: 15008
    protocol: HBONE

  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: waypoint-options
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: waypoint-options

data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: 5m
                memory: 50Mi
              limits:
                cpu: 10m
                memory: 100Mi
