apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - https://raw.githubusercontent.com/istio/istio/release-1.30/samples/addons/grafana.yaml

patches:
  # Patch the Grafana Deployment to install the Quickwit Plugin
  - target:
      kind: Deployment
      name: grafana
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GF_INSTALL_PLUGINS
          value: "https://github.com/quickwit-oss/quickwit-datasource/releases/download/v0.6.3/quickwit-quickwit-datasource-0.6.3.zip;quickwit-quickwit-datasource"
