---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key-secret
  data:
    - secretKey: api-key
      remoteRef:
        key: prod/tls/frontend
        property: cloudflare-api-token
