---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: weave-values
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterExternalSecret
  target:
    name: weave-secret-values
    template:
      engineVersion: v2
      data:
        values.yaml: |
          adminUser:
            create: true
            username: {{ .username }}
            passwordHash: "{{ .hash }}"
  data:
    - secretKey: username
      remoteRef:
        key: dev/flux-system/weave
        property: username
    - secretKey: hash
      remoteRef:
        key: dev/flux-system/weave
        property: passwordHash
