apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: cert-manager
spec:
  secretName: wildcard-tls-secret
  issuerRef:
    # Wildcard certificates require DNS01 challenge
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.example.com"
    - "example.com"
  privateKey:
    algorithm: RSA
    size: 2048
